import Link from 'next/link';
import { BandwidthDemo } from '@/components/DeviceLab';

export const metadata = {
  title: 'Findings',
  description:
    'Every result, with the checks that produced it. Two of the four tests I planned did not work, and both are written up.',
};

export default function FindingsPage() {
  return (
    <div className="wrap section prose">
      <p className="eyebrow">Four tests · two of them failed</p>
      <h1>What held up, and what did not</h1>
      <p className="lede">
        A tool that grades other people&rsquo;s data has to show its own working. This page has
        every number the project produced, including the two tests that did not survive contact
        with the data.
      </p>
      <p className="note">
        Everything here is regenerated by running{' '}
        <code>python -m validate.run_all</code> against the datasets. The machine readable
        version lives in{' '}
        <a href="https://github.com/aaryavvatts-lab/eeg-artifact-scope/blob/main/SCORECARD.md">
          SCORECARD.md
        </a>
        .
      </p>

      <h2>Test one: does it find blinks that definitely happened?</h2>
      <p>
        Thirty people blinked on a beep, twenty times per recording, on four headsets at once.
        The beep times are stored in the files, so this is a straight check against events that
        are known to have occurred.
      </p>

      <div className="scroll">
        <table>
          <caption>
            Recall is the share of cued blinks the detector found. Detections per cue near 1.0
            means one detection per blink.
          </caption>
          <thead>
            <tr>
              <th>Headset</th>
              <th className="num">Blinks found</th>
              <th className="num">Detections per blink</th>
              <th className="num">Jaw clench, task against rest</th>
              <th className="num">Recordings</th>
            </tr>
          </thead>
          <tbody>
            <tr><td>DSI-24</td><td className="num">88.3%</td><td className="num">1.02</td><td className="num">26.9×</td><td className="num">30</td></tr>
            <tr><td>Muse 2</td><td className="num">95.0%</td><td className="num">1.04</td><td className="num">25.3×</td><td className="num">26</td></tr>
            <tr><td>MindWave 2</td><td className="num">100%</td><td className="num">1.12</td><td className="num">44.9×</td><td className="num">30</td></tr>
            <tr><td>BrainLink Pro</td><td className="num">99.0%</td><td className="num">1.11</td><td className="num">89.1×</td><td className="num">30</td></tr>
          </tbody>
        </table>
      </div>

      <h3>Why there is no precision column</h3>
      <p>
        The obvious thing to report is precision: of the blinks it flagged, how many were real.
        That number cannot be computed here, and reporting it anyway would be misleading.
      </p>
      <p>
        People blink on their own between the beeps. Those detections are correct, but they do
        not line up with a cue, so scoring them as mistakes would make a working detector look
        broken. Getting a true precision figure needs someone to watch video of every second and
        mark each real blink, which this dataset does not include. Recall and detections per
        blink are what the data can actually support, so those are what is shown.
      </p>

      <h2>Test two: does it work without eye electrodes?</h2>
      <p>
        This is the case that matters in practice. Research systems often have electrodes placed
        specifically to record eye movement. Consumer headsets never do. If the detector only
        worked with them it would be useless for most of the hardware people own.
      </p>
      <p>
        One dataset has both, so the two can be compared on the same recording, second by second.
        Across six people, blink detection using only ordinary EEG channels agreed with the
        dedicated eye electrodes with an F1 of <strong>0.78</strong>, and found{' '}
        <strong>93%</strong> as many blinks overall.
      </p>
      <p>
        As a second opinion I ran MNE&rsquo;s own eye artifact finder over the same recordings.
        Agreement with that was <strong>0.78</strong> as well. Using an independent tool matters
        here, because otherwise the check is my code agreeing with my code.
      </p>

      <h2>Test three: does the score react to real contamination?</h2>
      <p>
        Finding an artifact is one thing. The score has to move in the right direction when
        contamination is genuinely present.
      </p>
      <p>
        Because each recording contains a resting minute and a task minute from the same person
        on the same headset, this can be tested as a matched pair. That controls for the person,
        the hardware, the electrode placement and the day, none of which a comparison between
        different people controls for.
      </p>

      <div className="scroll">
        <table>
          <caption>
            How far the score fell between a person resting and the same person on task.
          </caption>
          <thead>
            <tr>
              <th>Headset</th>
              <th>Task</th>
              <th className="num">Points lost</th>
              <th className="num">People who scored worse</th>
              <th className="num">Effect size</th>
            </tr>
          </thead>
          <tbody>
            <tr><td>DSI-24</td><td>jaw clench</td><td className="num">21.3</td><td className="num">30 of 30</td><td className="num">3.4</td></tr>
            <tr><td>Muse 2</td><td>jaw clench</td><td className="num">23.5</td><td className="num">26 of 26</td><td className="num">3.9</td></tr>
            <tr><td>MindWave 2</td><td>jaw clench</td><td className="num">29.2</td><td className="num">30 of 30</td><td className="num">8.1</td></tr>
            <tr><td>BrainLink Pro</td><td>jaw clench</td><td className="num">27.7</td><td className="num">30 of 30</td><td className="num">7.4</td></tr>
            <tr><td>DSI-24</td><td>blinking</td><td className="num">1.8</td><td className="num">18 of 30</td><td className="num">0.2</td></tr>
            <tr><td>Muse 2</td><td>blinking</td><td className="num">6.2</td><td className="num">19 of 26</td><td className="num">0.7</td></tr>
            <tr><td>MindWave 2</td><td>blinking</td><td className="num">8.4</td><td className="num">29 of 30</td><td className="num">3.0</td></tr>
            <tr><td>BrainLink Pro</td><td>blinking</td><td className="num">7.9</td><td className="num">30 of 30</td><td className="num">4.8</td></tr>
          </tbody>
        </table>
      </div>

      <p>
        Clenching costs 21 to 29 points and every single person scored worse. Blinking costs far
        less, and on the research cap it barely registers.
      </p>
      <p>
        That gap is not a bug, though it took some thought to be sure. Twenty cued blinks a
        minute is close to the rate people blink anyway, and blinks are removable. A minute of
        clenching is genuinely destructive. A quality score that treated normal blinking as a
        crisis would cry wolf on almost every recording ever made.
      </p>
      <p>
        The weak result on the DSI is partly that its dry electrodes are noisy at rest, so the
        resting minute it is compared against was not that clean to begin with.
      </p>

      <h2>Test four: the one that could not be run</h2>
      <p>
        The fourth plan was the strongest of the four. One dataset contains clean EEG, the same
        EEG with eye artifact added, and the original clean version kept separately. With the
        original you can measure not just whether an artifact was found but how much of the real
        signal survives cleaning.
      </p>
      <p>
        That file cannot be recovered. The archive published on the repository is truncated. It
        lists 52,453,907 bytes of contents but the file itself is 46,757,186 bytes, which matches
        the size the repository reports, so the download is complete and the hosted copy is
        short. The clean recording fails its checksum with about 17 MB of the expected 23 MB
        present. Two different extraction tools fail in the same place, which points at the
        archive rather than at my machine.
      </p>
      <p>
        The other two files came out intact, so a smaller test was still possible: given EEG with
        eye artifact added at known times, does the tool flag those moments? It found{' '}
        <strong>70%</strong> of them across 38 recordings.
      </p>
      <p className="note flag">
        One detail worth reporting rather than hiding. The artifact in that dataset is sideways
        eye movement, not blinking. Most of its energy sits below 1 Hz, and there are only two to
        four events in each half minute. Scoring a blink detector against it and calling the
        result a failure would be measuring the wrong thing, so the number above is the whole
        pipeline rather than the blink detector alone.
      </p>

      <h2>The test that produced nothing</h2>
      <p>
        One of the four datasets splits its recordings into a clean group and a noisy group. That
        looked like a ready made check on whether the quality score separates good recordings
        from bad ones.
      </p>
      <p>
        It does not work. I measured seven standard signal quality metrics across all forty
        people. None of them separates the two groups.
      </p>

      <div className="scroll">
        <table>
          <caption>
            Separation is how far above chance each metric gets. Zero is coin flipping.
          </caption>
          <thead>
            <tr><th>Metric</th><th className="num">Separation above chance</th></tr>
          </thead>
          <tbody>
            <tr><td>Sample to sample step size</td><td className="num">0.27</td></tr>
            <tr><td>Slow drift</td><td className="num">0.17</td></tr>
            <tr><td>Quality score</td><td className="num">0.15</td></tr>
            <tr><td>Alpha rhythm size</td><td className="num">0.14</td></tr>
            <tr><td>Mains hum</td><td className="num">0.02</td></tr>
            <tr><td>Overall signal size</td><td className="num">0.02</td></tr>
            <tr><td>High frequency power</td><td className="num">0.00</td></tr>
          </tbody>
        </table>
      </div>

      <p>
        Two other things about that dataset point the same way. Sixteen of its channels are named
        as if they were unused spare inputs, but they carry real signal and behave the same as
        the named ones. And its named electrodes agree with each other only weakly, far less than
        electrodes sharing a reference on a real head normally do.
      </p>
      <p>
        I am not claiming the dataset is wrong. I am reporting that I could not reproduce the
        distinction its documentation describes, and that I therefore did not use it as a check.
        Test three above replaced it, and the matched pair design it uses is stronger anyway.
      </p>

      <h2>Sample rate is not the same as usable bandwidth</h2>
      <p>
        This started as a bug and turned into one of the more useful things the tool does.
      </p>
      <p>
        Muscle activity is fast, so you look for it high in the frequency range. One dataset
        samples quickly enough to reach that range, so the detector went and measured it, and
        reported 17% muscle contamination on every channel of every person.
      </p>
      <p>
        The recordings had been filtered before being saved. Above about 38 Hz there is nothing
        left but electrical noise, and the detector was faithfully measuring noise. Sampling
        speed tells you the highest frequency a file <em>could</em> contain, not the highest it
        does.
      </p>
      <BandwidthDemo />
      <p>
        The tool now works out where each recording actually ends and refuses to measure above
        it, saying so in the report instead of inventing a number. If you hand it a heavily
        filtered file it will tell you that muscle cannot be assessed, which is the honest
        answer.
      </p>

      <h2>What I would still want</h2>
      <p>
        A precision figure needs video annotated second by second, which none of these datasets
        include. Everything reported here rests on recordings from a small number of labs, so
        the thresholds may not transfer to hardware or populations that behave differently.
        Clinical EEG from people with neurological conditions was not tested at all, and there is
        no reason to assume thresholds tuned on healthy adults carry over.
      </p>
      <p>
        The comparison between rules and a trained model is written and ready to run against the
        cued labels, and has not been done yet. It will be reported here either way, including if
        the model loses.
      </p>

      <div className="cta-row">
        <Link className="btn" href="/methods">How the detectors work</Link>
        <Link className="btn ghost" href="/data">Where the data came from</Link>
      </div>
    </div>
  );
}
