"""Run the whole validation suite and write benchmark.json + SCORECARD.md.

    python -m validate.run_all [--quick] [--subjects N]

``benchmark.json`` is copied into the web app so the Device Report Card shows
measured numbers rather than assertions.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

from . import (
    device_report_card,
    v1_cued_events,
    v2_reference_free,
    v3_dataset03_null,
    v3_paired_rest_task,
    v4_semisim,
)
from .common import ROOT

OUT_DIR = ROOT / "outputs"
BENCHMARK = OUT_DIR / "benchmark.json"
SCORECARD = ROOT / "SCORECARD.md"


def _fmt(summary: dict | None, pct: bool = False, digits: int = 1) -> str:
    """Render a summarise() dict as 'mean ± ci (n=…)'."""
    if not summary or summary.get("mean") is None:
        return "n/a"
    mean = summary["mean"]
    ci = summary.get("ci95")
    if pct:
        body = f"{mean:.1%}"
        if ci:
            body += f" [{ci[0]:.0%}–{ci[1]:.0%}]"
    else:
        body = f"{mean:.{digits}f}"
        if ci:
            body += f" [{ci[0]:.{digits}f}–{ci[1]:.{digits}f}]"
    return f"{body} (n={summary['n']})"


def write_scorecard(bench: dict) -> None:
    L: list[str] = []
    A = L.append

    A("# Validation scorecard")
    A("")
    A(
        "Generated by `python -m validate.run_all`. Every number here is measured "
        "against ground truth in the datasets, and the caveats are part of the "
        "result rather than footnotes to it."
    )
    A("")
    A(f"*Generated {bench['generated_at']} · eegscope {bench['version']}*")
    A("")

    # ---- V1 -----------------------------------------------------------
    v1 = bench.get("v1_cued_events", {})
    A("## V1 — Detection vs cued ground truth (dataset 01)")
    A("")
    A(
        "30 subjects performed 20 cued eye blinks and 20 cued jaw clenches, "
        "3 s apart, on five headsets at once. Cue times come from the EDF "
        "annotations."
    )
    A("")
    A("| Device | Tier | Blink recall | Detections per cue | Jaw: task vs rest |")
    A("|---|---|---|---|---|")
    for d in v1.get("devices", {}).values():
        A(
            f"| {d['label']} | {d['tier']} | {_fmt(d['blink']['recall_of_cued'], pct=True)} "
            f"| {_fmt(d['blink']['detections_per_cue'], digits=2)} "
            f"| {d['jaw'].get('task_vs_rest_ratio') or 'n/a'}× |"
        )
    A("")
    A(
        "> **Why no precision column.** Subjects blink spontaneously between "
        "cues, and those detections are correct. Scoring them as false "
        "positives would understate the detector; without frame-by-frame video "
        "annotation, recall and detections-per-cue are what the data supports. "
        "A detections-per-cue near 1.00 is the calibration target."
    )
    A("")

    # ---- V2 -----------------------------------------------------------
    v2 = bench.get("v2_reference_free", {})
    A("## V2 — Blink detection without EOG electrodes (dataset 02)")
    A("")
    if v2.get("skipped"):
        A(f"Skipped: {v2['skipped']}")
    else:
        s = v2.get("summary", {})
        A(
            "No consumer headset has EOG electrodes, so blinks must be found "
            "from frontal EEG alone. Dataset 02 has both, so the two paths can "
            "be compared on the same recording."
        )
        A("")
        A("| Comparison | F1 |")
        A("|---|---|")
        A(f"| Frontal-EEG-only vs the recording's own VEOG/HEOG | {_fmt(s.get('f1_vs_eog_channels'), digits=3)} |")
        A(f"| Frontal-EEG-only vs MNE `find_eog_events` | {_fmt(s.get('f1_vs_mne'), digits=3)} |")
        A("")
        A(
            "MNE is used as an independent reference here, so this is a "
            "cross-check rather than the code agreeing with itself."
        )
    A("")

    # ---- V3 -----------------------------------------------------------
    v3 = bench.get("v3_paired_rest_task", {})
    A("## V3 — Does the score respond to real contamination? (dataset 01)")
    A("")
    A(
        "Paired within-recording: the same subject on the same device, one "
        "minute at rest versus one minute of cued artifacts. This controls for "
        "subject, hardware, placement and session."
    )
    A("")
    A("| Device | Task | Rest score | Task score | Drop | Correct direction |")
    A("|---|---|---|---|---|---|")
    for r in v3.get("results", {}).values():
        if not r["n_subjects"]:
            continue
        A(
            f"| {r['device']} | {r['task']} | {_fmt(r['rest_score'])} "
            f"| {_fmt(r['task_score'])} | {_fmt(r['score_drop'])} "
            f"| {r['n_task_scored_worse']}/{r['n_subjects']} |"
        )
    A("")

    # ---- V3b ----------------------------------------------------------
    v3b = bench.get("v3_dataset03_null", {})
    A("## V3b — Dataset 03 clean vs noisy: a null result")
    A("")
    if v3b.get("skipped"):
        A(f"Skipped: {v3b['skipped']}")
    else:
        A(
            "Dataset 03 labels sub01–30 clean and sub31–40 noisy. **The groups "
            "do not separate on any standard metric.** This is reported rather "
            "than dropped, because it is the reason V3 uses a paired "
            "within-recording design instead."
        )
        A("")
        A("| Metric | Clean | Noisy | AUC | Separation over chance |")
        A("|---|---|---|---|---|")
        for k, v in v3b.get("metrics", {}).items():
            A(
                f"| {k} | {_fmt(v['clean'], digits=2)} | {_fmt(v['noisy'], digits=2)} "
                f"| {v['auc_clean_over_noisy']} | {v['separation']} |"
            )
        A("")
        if v3b.get("bandwidth_note"):
            A(f"> {v3b['bandwidth_note']}")
    A("")

    # ---- V4 -----------------------------------------------------------
    v4 = bench.get("v4_semisim", {})
    A("## V4 — Detection vs a known injected artifact (dataset 04)")
    A("")
    if v4.get("skipped"):
        A(f"Skipped: {v4['skipped']}")
    else:
        A(f"> **Reduced scope.** {v4['scope_note']}")
        A("")
        A(f"> **The artifact is not a blink.** {v4['artifact_note']}")
        A("")
        A("| Measure | Value |")
        A("|---|---|")
        A(f"| Simulations | {v4.get('n_simulations', 0)} |")
        A(f"| Injected artifacts | {v4.get('n_injected_artifacts', 0)} |")
        A(f"| Recall, any detector | {_fmt(v4.get('recall_any_detector'), pct=True)} |")
        A(f"| Recall, drift detector | {_fmt(v4.get('recall_drift_detector'), pct=True)} |")
        A(f"| Recall, blink detector | {_fmt(v4.get('recall_blink_detector'), pct=True)} |")
    A("")

    # ---- Device report card -------------------------------------------
    rc = bench.get("device_report_card", {})
    A("## Device Report Card")
    A("")
    A(
        "The same person, the same cued blink, the same instant — recorded on "
        "five headsets at once."
    )
    A("")
    A("| Device | Tier | Ch | Blink amplitude | Blink vs background | Jaw minute usable | Grade |")
    A("|---|---|---|---|---|---|---|")
    for d in rc.get("devices", {}).values():
        A(
            f"| {d['label']} | {d['tier']} | {d['channels']} "
            f"| {_fmt(d['blink_amplitude_uv'])} µV "
            f"| {_fmt(d['blink_to_background_ratio'], digits=1)}× "
            f"| {_fmt(d['jaw_usable_fraction'], pct=True)} "
            f"| {d.get('jaw_grade') or 'n/a'} |"
        )
    A("")
    if rc.get("caveat"):
        A(f"> {rc['caveat']}")
    A("")

    SCORECARD.write_text("\n".join(L) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--quick", action="store_true", help="use 8 subjects for a fast run")
    ap.add_argument("--subjects", type=int, default=None, help="cap subjects per dataset")
    args = ap.parse_args(argv)

    n = args.subjects if args.subjects else (8 if args.quick else None)
    OUT_DIR.mkdir(exist_ok=True)

    from eegscope import __version__ as version  # noqa: PLC0415

    bench: dict = {
        "generated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "version": version,
        "subjects_per_dataset": n or "all",
    }

    stages = [
        ("v1_cued_events", "V1  detection vs cued ground truth", lambda: v1_cued_events.run(n)),
        ("v2_reference_free", "V2  blink detection without EOG", lambda: v2_reference_free.run(min(n or 6, 6))),
        ("v3_paired_rest_task", "V3  paired rest vs cued artifact", lambda: v3_paired_rest_task.run(n)),
        ("v3_dataset03_null", "V3b dataset 03 clean vs noisy", v3_dataset03_null.run),
        ("v4_semisim", "V4  detection vs injected artifact", v4_semisim.run),
        ("device_report_card", "RC  device report card", lambda: device_report_card.run(n)),
    ]

    for key, title, fn in stages:
        print(f"\n{title}")
        t0 = time.time()
        try:
            bench[key] = fn()
        except Exception as exc:  # a broken stage must not lose the others
            print(f"  FAILED: {type(exc).__name__}: {exc}", file=sys.stderr)
            bench[key] = {"error": f"{type(exc).__name__}: {exc}"}
        print(f"  ({time.time() - t0:.1f}s)")

    BENCHMARK.write_text(json.dumps(bench, indent=2), encoding="utf-8")
    write_scorecard(bench)

    print(f"\nWrote {BENCHMARK.relative_to(ROOT)}")
    print(f"Wrote {SCORECARD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
